version: "3.8"
services:

  cloud-server:
    build: .
    image: cloud-server
    ports:
      - "9999:9999"
    networks:
      - host

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - host

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - host

  postgres:
    image: postgres
    volumes:
      - ./src/main/resources/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: card_issuer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - host

  card-issuer:
    build: ../card-issuer
    image: card-issuer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - cloud-server
      - kafka
    networks:
      - host

  notification:
    build: ../notification
    image: notification
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
    networks:
      - host

  client-service:
    build: ../client-service
    image: client-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - kafka
      - cloud-server
    networks:
      - host
networks:
  host:
    driver: bridge