server:
  port: 8084
spring:
  application:
    name: client-service
  datasource:
    url: jdbc:postgresql://postgres:5432/card_issuer?currentSchema=bank_client
    username: bank_client_user
    password: bank_client_user_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  liquibase:
    change-log: liquibase/db-changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    caffeine:
      spec:
        expireAfterWrite: 15m
kafka:
  bootstrapAddress: kafka:9092
  group:
    id: server.broadcast
  enabled: true
  topic:
    to-notification: to_notification
logging:
  level:
    ROOT: INFO
eureka:
  client:
    service-url:
      defaultZone: http://cloud-server:9999/eureka