CREATE ROLE card_issuer_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'card_issuer_user_password';
CREATE SCHEMA card_issuer AUTHORIZATION card_issuer_user;

CREATE ROLE bank_client_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'bank_client_user_password';
CREATE SCHEMA bank_client AUTHORIZATION bank_client_user;

CREATE ROLE notification_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'notification_password';
CREATE SCHEMA notification AUTHORIZATION notification_user;



