server:
  port: 8080
spring:
  cache:
    caffeine:
      spec:
        expireAfterWrite: 15m
  application:
    name: card-issuer
  datasource:
    url: jdbc:postgresql://postgres:5432/card_issuer?currentSchema=card_issuer
    username: card_issuer_user
    password: card_issuer_user_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://cloud-server:9999/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

logging:
  level:
    ROOT: INFO
