spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: notification_user
    password: notification_password
    url: jdbc:postgresql://postgres:5432/card_issuer?currentSchema=notification
  application:
    name: notification
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: liquibase/db-changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8082

kafka:
  bootstrapAddress: kafka:9092
  group:
    id: server.broadcast
  enabled: true
  topic:
    to-notification: to_notification

logging:
  level:
    ROOT: INFO

