### Account

GET http://localhost:8082/api/account

###
GET http://localhost:8082/api/account/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6Ik1TX0NMSUVOVCIsInN0YXR1cyI6IkFDVElWRSIsImV4cCI6MjIxNjIzOTAyMn0.Aj-UHmdBosUrf12BrXqn3dsGtXwn0QgBF-q6KP-LvpI

###
GET http://localhost:8082/api/account/3/balance?date=1638806337

### Operation

POST http://localhost:8082/api/operation
Content-Type: application/json

{
  "initiatorId": 1,
  "operationType": "TOP_UP",
  "debitAccountId": 3,
  "sum": 10.00
}

<> 2021-12-06T173218.201.json
<> 2021-12-05T040443.201.json
<> 2021-12-05T032843.201.json

###
POST http://localhost:8082/api/operation
Content-Type: application/json

{
  "initiatorId": 1,
  "operationType": "WITHDRAW",
  "creditAccountId": 3,
  "sum": 5.00
}

<> 2021-12-05T035511.201.json
<> 2021-12-05T034953.500.json


###
POST http://localhost:8082/api/operation
Content-Type: application/json

{
  "initiatorId": 1,
  "operationType": "PAYMENT",
  "debitAccountId": 4,
  "creditAccountId": 3,
  "sum": 5.00
}

<> 2021-12-06T173259.201.json
<> 2021-12-05T222810.201.json
<> 2021-12-05T222729.201.json
<> 2021-12-05T033028.201.json

###
POST http://localhost:8082/api/operation
Content-Type: application/json

{
  "initiatorId": 1,
  "operationType": "REFUND",
  "debitAccountId": 3,
  "creditAccountId": 4,
  "sum": 5.00
}

<> 2021-12-05T222529.201.json

###
GET http://localhost:8082/api/operation/303
Content-Type: application/json
